#ifndef CONHDL_H
#define CONHDL_H

#include <Windows.h>

enum Color {
	BLACK = 0,
	WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	BLUE = FOREGROUND_BLUE,
	RED = FOREGROUND_RED,
	GREEN = FOREGROUND_GREEN,
	MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
	CYAN = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY,
	YELLOW = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_INTENSITY
};

void gotoxy(int x, int y);
void set_color(enum Color color);
void clrcon();
void clrline();
void putc_at(char c, int x, int y, enum Color color);

#endif // CONHDL_H